# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interaction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='interaction.proto',
  package='interaction',
  syntax='proto3',
  serialized_options=b'\n\023io.grpc.interactionB\rInteractProtoP\001\242\002\002ST',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11interaction.proto\x12\x0binteraction\"%\n\x13RobotConnectRequest\x12\x0e\n\x06status\x18\x01 \x01(\t\"#\n\x11RobotConnectReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"4\n\x14TabletConnectRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06gender\x18\x02 \x01(\t\"$\n\x12TabletConnectReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1f\n\nRobotInput\x12\x11\n\tutterance\x18\x01 \x01(\t\" \n\x0bRobotOutput\x12\x11\n\tutterance\x18\x01 \x01(\t\"\x1a\n\x0bTabletInput\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x1e\n\x0cTabletOutput\x12\x0e\n\x06status\x18\x01 \x01(\t2\xbe\x02\n\x08Interact\x12S\n\r_RobotConnect\x12 .interaction.RobotConnectRequest\x1a\x1e.interaction.RobotConnectReply\"\x00\x12U\n\rTabletConnect\x12!.interaction.TabletConnectRequest\x1a\x1f.interaction.TabletConnectReply\"\x00\x12\x41\n\n_RobotSend\x12\x17.interaction.RobotInput\x1a\x18.interaction.RobotOutput\"\x00\x12\x43\n\nTabletSend\x12\x18.interaction.TabletInput\x1a\x19.interaction.TabletOutput\"\x00\x42+\n\x13io.grpc.interactionB\rInteractProtoP\x01\xa2\x02\x02STb\x06proto3'
)




_ROBOTCONNECTREQUEST = _descriptor.Descriptor(
  name='RobotConnectRequest',
  full_name='interaction.RobotConnectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='interaction.RobotConnectRequest.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=71,
)


_ROBOTCONNECTREPLY = _descriptor.Descriptor(
  name='RobotConnectReply',
  full_name='interaction.RobotConnectReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='interaction.RobotConnectReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=108,
)


_TABLETCONNECTREQUEST = _descriptor.Descriptor(
  name='TabletConnectRequest',
  full_name='interaction.TabletConnectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='interaction.TabletConnectRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gender', full_name='interaction.TabletConnectRequest.gender', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=162,
)


_TABLETCONNECTREPLY = _descriptor.Descriptor(
  name='TabletConnectReply',
  full_name='interaction.TabletConnectReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='interaction.TabletConnectReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=200,
)


_ROBOTINPUT = _descriptor.Descriptor(
  name='RobotInput',
  full_name='interaction.RobotInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='utterance', full_name='interaction.RobotInput.utterance', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=233,
)


_ROBOTOUTPUT = _descriptor.Descriptor(
  name='RobotOutput',
  full_name='interaction.RobotOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='utterance', full_name='interaction.RobotOutput.utterance', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=267,
)


_TABLETINPUT = _descriptor.Descriptor(
  name='TabletInput',
  full_name='interaction.TabletInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='interaction.TabletInput.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=295,
)


_TABLETOUTPUT = _descriptor.Descriptor(
  name='TabletOutput',
  full_name='interaction.TabletOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='interaction.TabletOutput.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=327,
)

DESCRIPTOR.message_types_by_name['RobotConnectRequest'] = _ROBOTCONNECTREQUEST
DESCRIPTOR.message_types_by_name['RobotConnectReply'] = _ROBOTCONNECTREPLY
DESCRIPTOR.message_types_by_name['TabletConnectRequest'] = _TABLETCONNECTREQUEST
DESCRIPTOR.message_types_by_name['TabletConnectReply'] = _TABLETCONNECTREPLY
DESCRIPTOR.message_types_by_name['RobotInput'] = _ROBOTINPUT
DESCRIPTOR.message_types_by_name['RobotOutput'] = _ROBOTOUTPUT
DESCRIPTOR.message_types_by_name['TabletInput'] = _TABLETINPUT
DESCRIPTOR.message_types_by_name['TabletOutput'] = _TABLETOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RobotConnectRequest = _reflection.GeneratedProtocolMessageType('RobotConnectRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTCONNECTREQUEST,
  '__module__' : 'interaction_pb2'
  # @@protoc_insertion_point(class_scope:interaction.RobotConnectRequest)
  })
_sym_db.RegisterMessage(RobotConnectRequest)

RobotConnectReply = _reflection.GeneratedProtocolMessageType('RobotConnectReply', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTCONNECTREPLY,
  '__module__' : 'interaction_pb2'
  # @@protoc_insertion_point(class_scope:interaction.RobotConnectReply)
  })
_sym_db.RegisterMessage(RobotConnectReply)

TabletConnectRequest = _reflection.GeneratedProtocolMessageType('TabletConnectRequest', (_message.Message,), {
  'DESCRIPTOR' : _TABLETCONNECTREQUEST,
  '__module__' : 'interaction_pb2'
  # @@protoc_insertion_point(class_scope:interaction.TabletConnectRequest)
  })
_sym_db.RegisterMessage(TabletConnectRequest)

TabletConnectReply = _reflection.GeneratedProtocolMessageType('TabletConnectReply', (_message.Message,), {
  'DESCRIPTOR' : _TABLETCONNECTREPLY,
  '__module__' : 'interaction_pb2'
  # @@protoc_insertion_point(class_scope:interaction.TabletConnectReply)
  })
_sym_db.RegisterMessage(TabletConnectReply)

RobotInput = _reflection.GeneratedProtocolMessageType('RobotInput', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTINPUT,
  '__module__' : 'interaction_pb2'
  # @@protoc_insertion_point(class_scope:interaction.RobotInput)
  })
_sym_db.RegisterMessage(RobotInput)

RobotOutput = _reflection.GeneratedProtocolMessageType('RobotOutput', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTOUTPUT,
  '__module__' : 'interaction_pb2'
  # @@protoc_insertion_point(class_scope:interaction.RobotOutput)
  })
_sym_db.RegisterMessage(RobotOutput)

TabletInput = _reflection.GeneratedProtocolMessageType('TabletInput', (_message.Message,), {
  'DESCRIPTOR' : _TABLETINPUT,
  '__module__' : 'interaction_pb2'
  # @@protoc_insertion_point(class_scope:interaction.TabletInput)
  })
_sym_db.RegisterMessage(TabletInput)

TabletOutput = _reflection.GeneratedProtocolMessageType('TabletOutput', (_message.Message,), {
  'DESCRIPTOR' : _TABLETOUTPUT,
  '__module__' : 'interaction_pb2'
  # @@protoc_insertion_point(class_scope:interaction.TabletOutput)
  })
_sym_db.RegisterMessage(TabletOutput)


DESCRIPTOR._options = None

_INTERACT = _descriptor.ServiceDescriptor(
  name='Interact',
  full_name='interaction.Interact',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=330,
  serialized_end=648,
  methods=[
  _descriptor.MethodDescriptor(
    name='_RobotConnect',
    full_name='interaction.Interact._RobotConnect',
    index=0,
    containing_service=None,
    input_type=_ROBOTCONNECTREQUEST,
    output_type=_ROBOTCONNECTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TabletConnect',
    full_name='interaction.Interact.TabletConnect',
    index=1,
    containing_service=None,
    input_type=_TABLETCONNECTREQUEST,
    output_type=_TABLETCONNECTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='_RobotSend',
    full_name='interaction.Interact._RobotSend',
    index=2,
    containing_service=None,
    input_type=_ROBOTINPUT,
    output_type=_ROBOTOUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TabletSend',
    full_name='interaction.Interact.TabletSend',
    index=3,
    containing_service=None,
    input_type=_TABLETINPUT,
    output_type=_TABLETOUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INTERACT)

DESCRIPTOR.services_by_name['Interact'] = _INTERACT

# @@protoc_insertion_point(module_scope)
